# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fuzail Palnak
email: fuzailpalnak@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  ML Learning

repository: "fuzailpalnak/fuzailpalnak.github.io"

baseurl: "" # the subpath of your site, e.g. /blog
url: https://fuzailpalnak.github.io # the base hostname & protocol for your site, e.g. http://example.com
github_username:  fuzailpalnak
disqus: fuzailpalnak-github-io
linkedin_username: fuzailpalnak

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.20.1"
#minimal_mistakes_skin: "air"
#theme: minima

plugins:
  - jekyll-feed
  - jekyll-include-cache

disable_disk_cache: True

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      words_per_minute: 250
      comments: true
      share: true
      related: true
      show_date: true
      author_profile: true

comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"

search: true

author:
  name     : "Fuzail"
  avatar   : "/assets/images/profile.jpg"
  bio      : "Software Engineer and Machine Learning Enthusiast"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/fuzail-palnak-b4962994/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/fuzailpalnak"
    - label: "Google Scholar"
      icon: "fas fa-user-graduate"
      url: "https://scholar.google.com/citations?user=xTmdJ_MAAAAJ&hl=en"

jekyll-archives:
  enabled:
    - categories
    - tags

paginate: 10

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - .idea/